# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRxSwiftStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRxSwiftStudy
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MVVMRxSwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMRxSwiftStudyUITests' do
    # Pods for testing
  end

end
