# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunesPreviewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesPreviewer
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Then'
  pod 'SnapKit'

  target 'iTunesPreviewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iTunesPreviewerUITests' do
    # Pods for testing
  end

end
