# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunesExplorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesExplorer
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Then'
  pod 'SnapKit'

  target 'iTunesExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iTunesExplorerUITests' do
    # Pods for testing
  end

end
